{% set name = "autopep8" %}
{% set version = "2.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ba4901621c7f94c6fce134437d577009886d5e3bfa46ee64e1d1d864a5b93cc2

build:
  number: 0
  noarch: python
  entry_points:
    - autopep8 = autopep8:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pycodestyle >=2.9.1
    - tomli

test:
  imports:
    - autopep8
  commands:
    - pip check
    - autopep8 --help
  requires:
    - pip

about:
  home: https://github.com/hhatto/autopep8
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: A tool that automatically formats Python code to conform to the PEP 8 style guide
  dev_url: https://github.com/hhatto/autopep8

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
