{% set name = "autopep8" %}
{% set version = "2.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8d6c87eba648fdcfc83e29b788910b8643171c395d9c4bcf115ece035b9c9dda

build:
  number: 1
  noarch: python
  entry_points:
    - autopep8 = autopep8:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation 

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - pycodestyle >=2.12.0
    - packaging
    - tomli

test:
  imports:
    - autopep8
  commands:
    - pip check
    - autopep8 --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/hhatto/autopep8
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: A tool that automatically formats Python code to conform to the PEP 8 style guide
  dev_url: https://github.com/hhatto/autopep8

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
