{% set name = "autopep8" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5cfe45eb3bef8662f6a3c7e28b7c0310c7310d340074b7f0f28f9810b44b7ef4

build:
  number: 0
  noarch: python
  entry_points:
    - autopep8 = autopep8:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pycodestyle >=2.12.0
    - packaging
    - tomli

test:
  imports:
    - autopep8
  commands:
    - pip check
    - autopep8 --help
  requires:
    - pip

about:
  home: https://github.com/hhatto/autopep8
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: A tool that automatically formats Python code to conform to the PEP 8 style guide
  dev_url: https://github.com/hhatto/autopep8

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
